Todo-list-front
Dvir916/todo-project2 pull request #1
Opened 2023-05-29 15:11 UTC by Dvir916

2023-05-31 08:03 UTC, GuyMozes7026 requested changes

2023-05-31 08:03 UTC, GuyMozes7026 commented on package.json
> +    "alertify": "^0.3.0",
uninstall

2023-05-31 08:03 UTC, GuyMozes7026 commented on package.json
> +    "@types/alertify": "^0.3.31"
uninstall

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/AddTodo.tsx
> +import "../App.css";
```suggestion
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/TodoList.tsx
> +import "../App.css";
```suggestion
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/AddTodo.tsx
> +import { useDispatch } from "react-redux/es/exports";
```suggestion
import { useDispatch } from "react-redux";
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/AddTodo.tsx
> +  const [tasksText, setTasksText] = useState("");
```
  const [taskText, setTaskText] = useState("");
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/AddTodo.tsx
> +  };
יכול להיות inline

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/AddTodo.tsx
> +  const addTask = (e: { preventDefault: () => void }) => {
תן לו טייפ אמיתי

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/interfaceTyps.ts
> +}
```
export interface Task {
  taskText: string;
  id: string;
  isComplete: boolean;
}
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/Task.tsx
> +const Task = ({ text, index }: { text: string; index: number }) => {
```
interface TaskItemProps {
  // ...
}
const TaskItem: React.FC<TaskItemProps> = ({ text, index }) => {
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/AddTodo.tsx
> +      alertify.alert("Error:", "the task must contain text!", function () {
```suggestion
      alertify.alert("Error:", "the task must contain text!", () => {
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/interfaceTypes.ts
> +export interface Tasks {
יחיד

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/App.css
אפשר למחוק

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/Task.tsx
> +  const tasksArray = useSelector((state: RootState) => state.tasks);
במקום לעשות פה עוד פעם useSelector, אפשר לקבל את כל ה task כ prop

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/Task.tsx
> +  return (
sx

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Components/TodoList.tsx
> +  const tasksArray = useSelector((state: RootState) => state.tasks);
`tasks`

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Redux/Store.tsx
> +export type AppDispatch = typeof store.dispatch;
```suggestion
// Infer the `RootState` type from the store itself
export type RootState = ReturnType<typeof store.getState>;
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Redux/Tasks.tsx
> +    earseTaskFromList: (state, action: PayloadAction<number>) => {
`eraseTaskFromList`

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Redux/Tasks.tsx
> +    changeStatus: (state, action: PayloadAction<number>) => {
toggleStatus

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/index.tsx
>  // or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
```suggestion
```

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/index.tsx
format

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/interfaceTypes.ts
> +  isComplate: boolean;
`isComplete`

2023-05-31 08:03 UTC, GuyMozes7026 commented on tsconfig.json
> +    "jsx": "preserve"
לבודק אם אפשר להחליף חזרה

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Redux/Store.tsx
סיומת ts

2023-05-31 08:03 UTC, GuyMozes7026 commented on src/Redux/Tasks.tsx
סיומת ts
ולקרוא לקובץ משהו עם slice

2023-05-31 13:03 UTC, Dvir916 commented on package.json
> +    "alertify": "^0.3.0",
טופל

2023-05-31 13:04 UTC, Dvir916 commented on package.json
> +    "@types/alertify": "^0.3.31"
טופל

2023-05-31 13:09 UTC, Dvir916 commented on src/Components/AddTodo.tsx
> +import "../App.css";
טופל

2023-05-31 13:09 UTC, Dvir916 commented on src/Components/TodoList.tsx
> +import "../App.css";
טופל

2023-05-31 13:10 UTC, Dvir916 commented on src/Components/AddTodo.tsx
> +import { useDispatch } from "react-redux/es/exports";
טופל

2023-05-31 13:10 UTC, Dvir916 commented on src/Components/AddTodo.tsx
> +  const [tasksText, setTasksText] = useState("");
טופל

2023-05-31 13:13 UTC, Dvir916 commented on src/Components/AddTodo.tsx
> +  };
כבר לא רלוונטי

2023-05-31 13:13 UTC, Dvir916 commented on src/Components/AddTodo.tsx
> +  const addTask = (e: { preventDefault: () => void }) => {
כבר לא רלוונטי

2023-05-31 13:14 UTC, Dvir916 commented on src/interfaceTyps.ts
> +}
טופל

2023-05-31 13:15 UTC, Dvir916 commented on src/Components/Task.tsx
> +const Task = ({ text, index }: { text: string; index: number }) => {
טופל

2023-05-31 13:17 UTC, Dvir916 commented on src/interfaceTypes.ts
> +export interface Tasks {
טופל

2023-05-31 14:07 UTC, Dvir916 commented on src/App.css
טופל

2023-05-31 14:44 UTC, Dvir916 commented on src/Components/Task.tsx
> +  const tasksArray = useSelector((state: RootState) => state.tasks);
טופל

2023-05-31 14:51 UTC, Dvir916 commented on src/Components/Task.tsx
> +  return (
טופל

2023-05-31 14:53 UTC, Dvir916 commented on src/Components/TodoList.tsx
> +  const tasksArray = useSelector((state: RootState) => state.tasks);
טופל

2023-05-31 14:55 UTC, Dvir916 commented on src/Redux/Tasks.tsx
> +    earseTaskFromList: (state, action: PayloadAction<number>) => {
טופל

2023-05-31 14:57 UTC, Dvir916 commented on src/Redux/Tasks.tsx
> +    changeStatus: (state, action: PayloadAction<number>) => {
טופל

2023-05-31 14:58 UTC, Dvir916 commented on src/index.tsx
טופל

2023-05-31 14:58 UTC, Dvir916 commented on src/interfaceTypes.ts
> +  isComplate: boolean;
טופל

2023-05-31 15:02 UTC, Dvir916 commented on tsconfig.json
> +    "jsx": "preserve"
טופל

2023-05-31 15:05 UTC, Dvir916 commented on src/Redux/Store.tsx
טופל

2023-05-31 15:14 UTC, Dvir916 commented on src/Redux/Tasks.tsx
יאללה נלך בשיטה שלך קראתי לקובץ בלי שייכות

2023-06-01 08:11 UTC, GuyMozes7026 commented on src/Redux/TaskSline.ts
> +      state.splice(
אפשר לעשות עם filter

2023-06-01 08:12 UTC, GuyMozes7026 commented on src/Components/Task.tsx
> +const strikethrough = styled(Box)({
לעשות עם אותיות גדולות ואז לא תצטרך לעשות עם Box component

2023-06-01 13:29 UTC, Dvir916 commented on src/Redux/TaskSline.ts
> +      state.splice(
טופל

2023-06-01 13:33 UTC, Dvir916 commented on src/Components/Task.tsx
> +const strikethrough = styled(Box)({
שיניתי את כולם לאות גדולה ואז קראתי להם כקומפוננטות חוץ מהBOX של הטקסט שיש בחירה בין שני אופציות עם קו אלכסוני או בלי אז השארתי אותם כCLASS

2023-06-01 13:35 UTC, Dvir916 commented on src/Components/Task.tsx
> +const strikethrough = styled(Box)({
<img width="166" alt="צילום מסך 2023-06-01 163403" src="https://github.com/Dvir916/todo-project2/assets/89272202/0ded8811-4e0f-4e47-a7e8-fcb323288b7e">

2023-06-06 08:11 UTC, GuyMozes7026 approved these changes

2023-06-06 08:14 UTC, merged