Front redux db
Dvir916/todo-project2 pull request #3
Opened 2023-06-06 11:36 UTC by Dvir916

2023-06-06 11:38 UTC, Dvir916 commented
https://github.com/Dvir916/Todo-List-Backend/pull/1

2023-06-06 15:32 UTC, GuyMozes7026 requested changes

2023-06-06 15:32 UTC, GuyMozes7026 commented on src/App.tsx
> +      <Box>
לא צריך את ה Box-ים, AppHeader הוא גם ככה Box בעצמו

2023-06-06 15:32 UTC, GuyMozes7026 commented on src/index.tsx
> +    <FetchProvider url="http://localhost:4000/Tasks">
ה url שאתה נותן לו אמור להיות ה url הכללי של ה backend, את ה tasks/ אתה תציין בקריאה ל useFetch

2023-06-06 15:32 UTC, GuyMozes7026 commented on src/Redux/TaskSlice.ts
> +      }
אין צורך בבדיקה, הגדרת את ה payload בתור מערך בלי אפשרות ל undefined או null או משהו
והערך הבוליאני של מערך, גם אם הוא ריק, זה true
```suggestion
      return action.payload;
```

2023-06-06 15:32 UTC, GuyMozes7026 commented on src/interfaceTypes.ts
> +  text : string;
מניח שבטעות הכנסת את זה בקונפליקטים אבל זה אמור להיות ביחיד ובלי רווח לפני הנקודותיים
(כמו שזה היה קודם פשוט)

2023-06-06 15:32 UTC, GuyMozes7026 commented on src/Redux/TaskSlice.ts
> +    insertDataFromDB: (state, action: PayloadAction<Tasks[]>) => {
השם לא צריך לציין את זה שזה מגיע מה-DB כי זה לא קשור למה שה-action תכלס עושה
ה-action עצמו פשוט משנה את הערך של tasks למה שנותנים לו אז שם הגיוני יהיה `setTasks`

2023-06-06 15:32 UTC, GuyMozes7026 commented on src/Redux/TaskSlice.ts
> +      action: PayloadAction<{ text: string; id: number }>
למה שינית את ה payload שיקבל גם id אם אתה לא משתמש ב id?

2023-06-06 15:32 UTC, GuyMozes7026 commented on src/Components/InitializeData.tsx
לא צריך קומפוננטה לזה, אפשר לעשות את זה ב App
אבל אם עושים כבר קומפוננטה כזאת היא צריכה לעטוף את שאר הקומפוננטות ולא פשוט לשבת מעליהן
כרגע יש לך מצב שבזמן טעינה כתוב ...Loading ומתחתיו רואים את תיבת הטקסט ורשימה ריקה

במקרה שלך נראה לי הגיוני לעשות בApp וזהו

2023-06-07 07:15 UTC, Dvir916 commented on src/App.tsx
> +      <Box>
טופל

2023-06-07 07:16 UTC, Dvir916 commented on src/index.tsx
> +    <FetchProvider url="http://localhost:4000/Tasks">
גם אם אני משתמש רק ב/task? בהתחלה שמתי כללי אבל אז ראיתי שזה סתם חוזר על עצמו

2023-06-07 07:24 UTC, Dvir916 commented on src/Redux/TaskSlice.ts
> +      }
ה payload יכול להיות undefined אבל אתה צודק כי בפעם הראשונה הוא מגדיר את הredux כ undefined אבל אז הוא נכנס עוד פעם לפונקציה ומגדיר את ה redux עם הנתונים.

2023-06-07 07:27 UTC, Dvir916 commented on src/interfaceTypes.ts
> +  text : string;
צודק, אבל זה מוזר כי זה עבד

2023-06-07 07:30 UTC, Dvir916 commented on src/Redux/TaskSlice.ts
> +    insertDataFromDB: (state, action: PayloadAction<Tasks[]>) => {
טופל

2023-06-07 08:11 UTC, Dvir916 commented on src/Redux/TaskSlice.ts
> +      action: PayloadAction<{ text: string; id: number }>
צודקת אני הייתי צריך להשתמש בו עכשיו שיניתי ואני משתמש בו

2023-06-07 08:17 UTC, Dvir916 commented on src/Components/InitializeData.tsx
סבבה הכנסתי את הקוד לAPP

2023-06-07 12:59 UTC, GuyMozes7026 commented on src/App.tsx
> +  const { get, data, loading } = useFetch("/Tasks", {}, []);
```
  const { get, data, loading } = useFetch<Task[]>("/Tasks", {}, []);
```

2023-06-07 13:03 UTC, GuyMozes7026 commented on src/interfaceTypes.ts
> +  text : string;
לא עשית ביחיד

2023-06-07 13:16 UTC, Dvir916 commented on src/interfaceTypes.ts
> +  text : string;
עכשיו טופל

2023-06-07 13:18 UTC, Dvir916 commented on src/App.tsx
> +  const { get, data, loading } = useFetch("/Tasks", {}, []);
טופל

2023-06-07 16:04 UTC, GuyMozes7026 approved these changes

2023-06-11 11:31 UTC, closed without merging